services:
  - hostname: orch
    type: ubuntu@24.04
    mode: NON_HA
    minContainers: 1
    maxContainers: 1
    verticalAutoscaling:
      minCpu: 1
      maxCpu: 2
      cpuMode: SHARED
      minRam: 2
      maxRam: 6
      minDisk: 10
      maxDisk: 30
